# Generated by Django 5.0.4 on 2024-06-30 13:08

import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル')),
                ('slide_show1', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='スライドショー1')),
                ('slide_show2', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='スライドショー2')),
                ('slide_show3', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='スライドショー3')),
                ('slide_show4', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='スライドショー4')),
                ('slide_show5', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='スライドショー5')),
                ('body', django_summernote.fields.SummernoteTextField(verbose_name='本文')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'verbose_name': '施工事例',
                'verbose_name_plural': '施工事例 一覧',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル')),
                ('body', django_summernote.fields.SummernoteTextField(verbose_name='本文')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ 一覧',
            },
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='サムネイル')),
                ('body', django_summernote.fields.SummernoteTextField(verbose_name='本文')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'verbose_name': '補助金',
                'verbose_name_plural': '補助金 一覧',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
